### ISSUE TITLE
Upgrade to Intel LLVM compilers

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UFS_UTILS#879] opened 2023-12-05 14:43 UTC
The 'classic' Intel compilers (`ifort`, `icc`, and `icpc`) are now discontinued and the new LLVM compilers (`ifx` and `icx`) are the only option starting with version 2024.  All supported machines with working versions of the LLVM compilers should be upgraded to the LLVM suite.

Per @junwang-noaa - try to use the 2024 version as the 2023 version has some bugs.

**Comment by GeorgeGayno-NOAA** [comment] 2024-08-20 20:50
Using 1056ef5, the unit tests were successfully run on Hercules and Hera. 

NOTE:  Setting `CMAKE_C_FLAGS_RELEASE "-O2"` (in `./CMakeLists.txt`) caused the `fre-nctools/tst_create_xgrid` unit test to 'seg fault'. For now, I will set `CMAKE_C_FLAGS_RELEASE "-O1"` for IntelLLVM

**Comment by GeorgeGayno-NOAA** [comment] 2024-08-22 19:37
@AlexanderRichert-NOAA - I want to update the Github workflows to use IntelLLVM. I think I completed part of the update at c10e85a. However, the libraries are built using https://github.com/GeorgeGayno-NOAA/UFS_UTILS/blob/intelLLVM/ci/spack.yaml. Can you or someone on the libraries team assist me with updating spack.yaml?

**Comment by GeorgeGayno-NOAA** [comment] 2024-08-22 21:08
Hash c10e85a was tested on Hercules. All regression tests were run:

- `global_cycle`, `ice_blend`, `ocnice_prep` and `snow2mdl` and `weight_gen` all passed.
- `chgres_cube` tests 6, 7, and 11 failed. All others passed.
- `cpld_gridgen` - all tests failed.

All failed tests had roundoff differences from their baselines.

**Comment by GeorgeGayno-NOAA** [comment] 2024-08-23 12:58
All regression tests were run on WCOSS2 using 9511885. All tests passed as expected.

**Comment by GeorgeGayno-NOAA** [comment] 2024-08-23 13:00
My preliminary tests show UFS_UTILS is working with the existing spack-stacks.

Will hold off on further work until it is determined whether new versions of spack-stack (that use IntelLLVM) will be implemented.

**Comment by GeorgeGayno-NOAA** [comment] 2024-08-28 12:44
> @AlexanderRichert-NOAA - I want to update the Github workflows to use IntelLLVM. I think I completed part of the update at [c10e85a](https://github.com/ufs-community/UFS_UTILS/commit/c10e85addabd951d10270da1d0744ed2a57dfa16). However, the libraries are built using https://github.com/GeorgeGayno-NOAA/UFS_UTILS/blob/intelLLVM/ci/spack.yaml. Can you or someone on the libraries team assist me with updating spack.yaml?

I tried updates at 56bf5e1 and 98f840a, but the spack build fails during the compilation of sigio library routine sigio_module.f. I also see numerous warnings concerning compiler options. For example:

`warning: unknown warning option '-Wc90-c99-compat'; did you mean '-Wc99-compat'? [-Wunknown-warning-option]`

**Comment by AlexanderRichert-NOAA** [comment] 2024-08-29 00:03
Ah yes, we added Intel OneAPI support to sigio but didn't actually do a release (right now it's failing because it's looking for fixed form because `-free` isn't being applied). I'll do a release shortly...

**Comment by GeorgeGayno-NOAA** [comment] 2024-09-30 20:14
Big changes to the `orog` code were merged from 'develop' to the branch at 7dff2c3.  The `grid_gen` regression tests were then run on Hercules. Tests 4 and 5 passed. Tests 1, 2, 3, 6 and 7 failed. The failed tests differed from the baseline, but the differences were considered 'round-off' in magnitude.

**Comment by GeorgeGayno-NOAA** [comment] 2024-10-22 17:50
> Ah yes, we added Intel OneAPI support to sigio but didn't actually do a release (right now it's failing because it's looking for fixed form because `-free` isn't being applied). I'll do a release shortly...

Thanks. I pointed to v2.3.3 at 0147b59, but now I am getting an error during the spack install. The error is: 

```
Cannot satisfy 'sigio@2.3.3'
        required because sigio@2.3.3 requested explicitly 
```

Any ideas?

**Comment by GeorgeGayno-NOAA** [comment] 2024-10-22 17:59
> > Ah yes, we added Intel OneAPI support to sigio but didn't actually do a release (right now it's failing because it's looking for fixed form because `-free` isn't being applied). I'll do a release shortly...
> 
> Thanks. I pointed to v2.3.3 at [0147b59](https://github.com/ufs-community/UFS_UTILS/commit/0147b590afef1fe20f8f1393ac1bb5aa942c495f), but now I am getting an error during the spack install. The error is:
> 
> ```
> Cannot satisfy 'sigio@2.3.3'
>         required because sigio@2.3.3 requested explicitly 
> ```
> 
> Any ideas?

Is this the issue? 2.3.2 is required.
https://github.com/JCSDA/spack-stack/blob/develop/configs/common/packages.yaml

**Comment by AlexanderRichert-NOAA** [comment] 2024-10-22 18:01
No, version 2.3.3 isn't in the JCSDA fork yet. Let me see if I can add that right now...

**Comment by AlexanderRichert-NOAA** [comment] 2024-10-22 18:09
It should work once https://github.com/JCSDA/spack/pull/480 is merged.

**Comment by AlexanderRichert-NOAA** [comment] 2024-10-22 20:18
(Done)

**Comment by GeorgeGayno-NOAA** [comment] 2024-10-23 15:15
> (Done)

Thanks. Now I am running into the same issue with sfcio v1.4.1. My unit tests no longer use sfcio, so I am removing it from the workflow.  But other users will need access to v1.4.2.

**Comment by AlexanderRichert-NOAA** [comment] 2024-10-23 22:01
sfcio 1.4.2 is now available under JCSDA Spack.

**Closed as completed** 2024-11-18 14:51 UTC

**Comment by GeorgeGayno-NOAA** [comment] 2024-11-18 18:11
@AlexanderRichert-NOAA - after I merged to develop, the spack build is breaking. It worked fine in the branch. Any idea what is going on?

https://github.com/ufs-community/UFS_UTILS/actions/runs/11898145099

**Comment by AlexanderRichert-NOAA** [comment] 2024-11-18 18:21
I'll take a look.

**Comment by AlexanderRichert-NOAA** [comment] 2024-11-18 23:20
See https://github.com/ufs-community/UFS_UTILS/pull/998
