### ISSUE TITLE
Measure test coverage as part of CI runs

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#293] opened 2021-02-13 12:33 UTC
We need to somehow measure and display test coverage as part of CI.

**Comment by kgerheiser** [comment] 2021-03-02 14:25
I was able to do this in Github by installing gcovr and passing `CMAKE_Fortran_FLAGS` for the necessary flags through the command line.

The issue is outputting the data. With Github Actions you can save artifacts as a `.zip`, but that's it. There's no way to directly view the HTML output. You have to manually download it to look at the results. 

There's https://about.codecov.io which is a service that does this and integrates into Github, but it requires paying for it.

So, my plan is to upload the `.html` files and you'll have to manually look at them.

**Comment by edwardhartnett** [comment] 2021-03-02 14:59
OK, that works for now, and maybe we can improve it later...

**Comment by kgerheiser** [comment] 2021-03-03 16:16
Fixed with #380 

@edwardhartnett there's this issue in the upload artifact Action to be able to view files in the browser, and hopefully it's coming. https://github.com/actions/upload-artifact/issues/14

**Comment by edwardhartnett** [comment] 2021-03-03 17:13
OK, in the meantime, what's the procedure for getting the package of html files?

**Comment by kgerheiser** [comment] 2021-03-03 17:28
You go to `Actions`, click on a workflow run, and it's listed on the bottom as `test-coverage`. Click on that and it downloads. 

See here, for example: 

https://github.com/NOAA-EMC/UFS_UTILS/actions/runs/618295926

**Comment by edwardhartnett** [comment] 2021-03-18 22:23
When I upload this and unzip, there is just one file, the main report file. But there should be a bunch more HTML files, one for each code file as well...

**Comment by kgerheiser** [comment] 2021-03-22 15:17
I was using the option `--html` which outputs just a single HTML file. The command `--html-details` makes a page for each file.

**Closed** 2021-03-23 14:07 UTC
Labels: test
